name: Docker Deploy

on:
    push:
        branches:
            - "master"


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Docker login
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker build
              run: docker build -t cau777/regex-designer-server .

            - name: Docker push
              run: docker push cau777/regex-designer-server:latest
